[tool.poetry]
name = "mypackage"
version = "0.1.0"
description = ""
authors = ["Anurag Mishra <mishra.anurag643@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
